// Generated by `bun run sync:types` from skelly-backend's src/appRouter.ts. Do not edit.
// When the backend's router changes, run the sync again and commit the result.

export declare const appRouter: import("@trpc/server").TRPCBuiltRouter<{
    ctx: {};
    meta: object;
    errorShape: import("@trpc/server").TRPCDefaultErrorShape;
    transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
    health: import("@trpc/server").TRPCBuiltRouter<{
        ctx: {};
        meta: object;
        errorShape: import("@trpc/server").TRPCDefaultErrorShape;
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        check: import("@trpc/server").TRPCQueryProcedure<{
            input: void;
            output: {
                app: string;
                status: string;
                timestamp: string;
                message: string;
            };
            meta: object;
        }>;
    }>>;
}>>;
export type AppRouter = typeof appRouter;
