// Copies the backend's emitted AppRouter contract into src/lib/app-router.d.ts.
// Run it whenever the backend's router changes, then commit the result. The admin never
// imports the backend's source, so a fresh clone typechecks and builds on its own.
import { $ } from "bun";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const backend = resolve(process.env.SKELLY_BACKEND ?? "../skelly-backend");
if (!existsSync(resolve(backend, "package.json"))) {
  console.error(`✖ no backend at ${backend}`);
  console.error("  Clone skelly-backend beside this repo, or set SKELLY_BACKEND=/path/to/skelly-backend.");
  process.exit(1);
}

await $`bun run types:emit`.cwd(backend);

const contract = readFileSync(resolve(backend, "dist/types/appRouter.d.ts"), "utf8");
const header =
  "// Generated by `bun run sync:types` from skelly-backend's src/appRouter.ts. Do not edit.\n" +
  "// When the backend's router changes, run the sync again and commit the result.\n\n";
writeFileSync("src/lib/app-router.d.ts", header + contract);
console.log(`✔ src/lib/app-router.d.ts synced from ${backend}`);
